In [3]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

/Users/nick/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [4]:
df = pd.read_csv("sdf_20.csv")
df.head()

user_parameters.immune_apoptosis_rate  \
0                              -1.549192   
1                              -1.549192   
2                              -1.549192   
3                              -1.549192   
4                              -1.549192   

   user_parameters.immune_migration_bias  user_parameters.immune_kill_rate  \
0                              -1.549192                         -1.549192   
1                              -1.549192                         -1.549192   
2                              -1.549192                         -1.549192   
3                              -1.549192                         -1.549192   
4                              -1.549192                         -1.549192   

   user_parameters.immune_attachment_lifetime  \
0                                   -1.549192   
1                                   -1.549192   
2                                   -1.549192   
3                                   -1.549192   
4                                   -1.549192   

   user_parameters.immune_attachment_rate  \
0                               -1.549192   
1                               -1.549192   
2                               -1.549192   
3                               -1.549192   
4                               -1.549192   

   user_parameters.oncoprotein_threshold     ev   cl  
0                              -1.549192   True   X1  
1                              -1.161894  False  NaN  
2                              -0.774596  False  NaN  
3                              -0.387298  False  NaN  
4                               0.000000   True   X1

In [12]:
def set_cl(row):
    return 0 if row['cl'] == 'X0' else 1

df_ev = df[df.ev == True]
df_ev['c'] = df.apply(lambda row: set_cl(row), axis=1)
df_train = df_ev.iloc[:,0:6]
df_target = df_ev.iloc[:, 8]
X = df_train.values
y = df_target.values



/Users/nick/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


user_parameters.immune_apoptosis_rate  \
6228                            -1.549192e+00   
6552                            -1.549192e+00   
7471                            -1.549192e+00   
7597                            -1.549192e+00   
7627                            -1.549192e+00   
7693                            -1.549192e+00   
7988                            -1.549192e+00   
8041                            -1.549192e+00   
8548                            -1.549192e+00   
8654                            -1.549192e+00   
9304                            -1.549192e+00   
9731                            -1.549192e+00   
10068                           -1.549192e+00   
10266                           -1.549192e+00   
10477                           -1.549192e+00   
11293                           -1.549192e+00   
11301                           -1.549192e+00   
11412                           -1.549192e+00   
11552                           -1.549192e+00   
12334                           -1.549192e+00   
13662                           -1.549192e+00   
14577                           -1.549192e+00   
15631                           -1.549192e+00   
15847                           -1.549192e+00   
17033                           -1.549192e+00   
18023                           -1.549192e+00   
18358                           -1.549192e+00   
18871                           -1.549192e+00   
19249                           -1.549192e+00   
19384                           -1.549192e+00   
...                                       ...   
291672                          -1.711271e-15   
291960                          -1.711271e-15   
291996                          -1.711271e-15   
292000                          -1.711271e-15   
292284                          -1.711271e-15   
292320                          -1.711271e-15   
292324                          -1.711271e-15   
292717                          -1.711271e-15   
294552                          -1.711271e-15   
294588                          -1.711271e-15   
294652                          -1.711271e-15   
294876                          -1.711271e-15   
294912                          -1.711271e-15   
294916                          -1.711271e-15   
295200                          -1.711271e-15   
295236                          -1.711271e-15   
295240                          -1.711271e-15   
331038                           3.872980e-01   
334513                           3.872980e-01   
338787                           3.872980e-01   
339130                           3.872980e-01   
340191                           3.872980e-01   
343170                           3.872980e-01   
343352                           3.872980e-01   
344243                           3.872980e-01   
344466                           3.872980e-01   
345187                           3.872980e-01   
351747                           3.872980e-01   
352251                           3.872980e-01   
354206                           3.872980e-01   

        user_parameters.immune_migration_bias  \
6228                                -1.549192   
6552                                -1.549192   
7471                                -1.161894   
7597                                -1.161894   
7627                                -1.161894   
7693                                -1.161894   
7988                                -1.161894   
8041                                -1.161894   
8548                                -1.161894   
8654                                -1.161894   
9304                                -1.161894   
9731                                -1.161894   
10068                               -1.161894   
10266                               -1.161894   
10477                               -1.161894   
11293                               -1.161894   
11301                               -1.161894   
11412                               -1.161894   
11552                               -1

In [60]:
X.shape

(1707, 6)

In [73]:
from sklearn.model_selection import cross_validate, RepeatedKFold
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0)

rkfold = RepeatedKFold(n_splits=5, n_repeats=3)

clf = RandomForestClassifier(random_state=42, n_estimators=100)
param_grid = {'criterion' : ['gini', 'entropy'], 'max_features' : ['auto', 'sqrt', 'log2', None]}
gs = GridSearchCV(estimator=clf, param_grid=param_grid, cv=rkfold)
gs.fit(X_train, y_train)

bs = gs.best_estimator_
y_true, y_pred = y_test, bs.predict(X_test)
print(classification_report(y_true, y_pred))

             precision    recall  f1-score   support

          0       0.86      0.85      0.85        85
          1       0.96      0.96      0.96       342

avg / total       0.94      0.94      0.94       427



In [76]:
import pickle
with open("./rf.pkl", 'wb') as f_out:
    pickle.dump(gs.best_estimator_, f_out)

In [78]:
with open ("./rf.pkl", 'rb') as f_in:
    rf = pickle.load(f_in)

y_true, y_pred = y_test, rf.predict(X_test)
print(classification_report(y_true, y_pred))

             precision    recall  f1-score   support

          0       0.86      0.85      0.85        85
          1       0.96      0.96      0.96       342

avg / total       0.94      0.94      0.94       427



In [86]:
p = rf.predict([X_test[0, :]])
p == 0

array([False])

In [101]:
from sklearn.preprocessing import StandardScaler
fdf = pd.read_csv("df.csv")

In [102]:
sfdf = fdf.iloc[:,0:6]
scaler = StandardScaler()
scaler.fit(sfdf.values)
scaler.transform(sfdf.values)

array([[-1.54919334, -1.54919334, -1.54919334, -1.54919334, -1.54919334,
        -1.54919334],
       [-1.54919334, -1.54919334, -1.54919334, -1.54919334, -1.54919334,
        -1.161895  ],
       [-1.54919334, -1.54919334, -1.54919334, -1.54919334, -1.54919334,
        -0.77459667],
       ...,
       [ 1.54919334,  1.54919334,  1.54919334,  1.54919334,  1.54919334,
         0.77459667],
       [ 1.54919334,  1.54919334,  1.54919334,  1.54919334,  1.54919334,
         1.161895  ],
       [ 1.54919334,  1.54919334,  1.54919334,  1.54919334,  1.54919334,
         1.54919334]])

In [97]:
fdf.values

array([[6.940e-06, 1.000e-01, 1.000e-02, 1.000e+01, 1.000e-02, 1.000e-01],
       [6.940e-06, 1.000e-01, 1.000e-02, 1.000e+01, 1.000e-02, 2.125e-01],
       [6.940e-06, 1.000e-01, 1.000e-02, 1.000e+01, 1.000e-02, 3.250e-01],
       ...,
       [6.940e-04, 9.000e-01, 1.000e+00, 9.000e+01, 1.000e+00, 7.750e-01],
       [6.940e-04, 9.000e-01, 1.000e+00, 9.000e+01, 1.000e+00, 8.875e-01],
       [6.940e-04, 9.000e-01, 1.000e+00, 9.000e+01, 1.000e+00, 1.000e+00]])

In [111]:
pt = fdf.values[4, 0:6]
pt = list(pt)
spt = scaler.transform([pt])
rf.predict(spt)

array([1])

In [112]:
fdf.values[4, :]

array([6.94e-06, 0.1, 0.01, 10, 0.01, 0.55, True, 'X1', 1.0], dtype=object)

In [114]:
with open("./scaler.pkl", 'wb') as f_out:
    pickle.dump(scaler, f_out)

In [115]:
with open ("./scaler.pkl", 'rb') as f_in:
    scaler = pickle.load(f_in)



In [116]:
scaler.transform([pt])

array([[-1.54919334, -1.54919334, -1.54919334, -1.54919334, -1.54919334,
         0.        ]])